import numpy as np

ERR = -1
STAND_BY = 0
SUB1_START = 1
SUB1_ONGOING = 2
SUB2_START = 3
SUB2_ONGOING = 4

sub_action_num = 2

sub_action_table_arm_ori = np.array([
    [STAND_BY, SUB1_START, STAND_BY, STAND_BY, STAND_BY],
    [STAND_BY, SUB1_ONGOING, SUB2_START, SUB2_START, ERR],
    [STAND_BY, SUB1_ONGOING, SUB2_START, SUB2_START, ERR],
    [STAND_BY, SUB1_START, SUB2_ONGOING, ERR, SUB1_START],
    [STAND_BY, ERR, SUB2_ONGOING, ERR, SUB1_START]
])
